- hosts: Docker
  tasks:
    - name: Copy contents of /opt/docker from ansibleHost to dockerHost
      copy:
        src: /home/Chakhree/docker/nodejs-pnpm-backend/
        dest: /home/Chakhree/docker/nodejs-pnpm-backend/
