- hosts: Docker
  tasks:
    - name: Copy expressjs-pnpm-backend from ansibleHost to aockerHost
      copy:
        src: /home/Chakhree/docker/expressjs-pnpm-backend/
        dest: /home/Chakhree/docker/expressjs-pnpm-backend/
    - name: Stop and remove expressjs-pnpm-container
      ansible.builtin.shell: |
        docker stop expressjs-pnpm-container
        docker rm expressjs-pnpm-container
      ignore_errors: true
    - name: Remove expressjs-pnpm-image
      ansible.builtin.shell: |
        docker rmi expressjs-pnpm-image
      ignore_errors: true
    - name: Create expressjs-pnpm-image
      ansible.builtin.shell: |
        docker build -t expressjs-pnpm-image /home/Chakhree/docker/expressjs-pnpm-backend/
    - name: Check expressjs-pnpm-image has been created
      ansible.builtin.shell: |
        docker image ls
    - name: Run expressjs-pnpm-container
      ansible.builtin.shell: |
        docker run -d --name expressjs-pnpm-container -p 3001:3000 expressjs-pnpm-image
