- hosts: Docker
  tasks:
    - name: Copy project from ansibleHost to aockerHost
      copy:
        src: /home/Chakhree/docker/nodejs-pnpm-backend/
        dest: /home/Chakhree/docker/nodejs-pnpm-backend/
    - name: stage 1
      ansible.builtin.shell: docker stop nodejs-pnpm-container 
      ansible.builtin.shell: docker rm nodejs-pnpm-container
    # - name: Stop and remove nodejs-pnpm-container
    #   ansible.builtin.shell: |
    #     docker stop nodejs-pnpm-container 
    #     docker rm nodejs-pnpm-container
    # - name: Remove nodejs-pnpm-image
    #   ansible.builtin.shell: |
    #     docker rmi nodejs-pnpm-image
    # - name: Create nodejs-pnpm-image
    #   ansible.builtin.shell: |
    #     docker build -t nodejs-pnpm-image /home/Chakhree/docker/nodejs-pnpm-backend/
    # - name: Check nodejs-pnpm-image has been created
    #   ansible.builtin.shell: |
    #     docker image ls
    # - name: Run nodejs-pnpm-container
    #   ansible.builtin.shell: |
    #     docker run -d --name nodejs-pnpm-container -p 3001:3000 nodejs-pnpm-image
